### ISSUE TITLE
why not just use celery task as selinon task?

### ISSUE THREAD

**Issue by dusteye** [selinon/selinon#43]
In the past few days, I have been searching and comparing list of distributed task flow engins support dynamic linking. At last, I found selinon is just what I want. It is a greate job! 
But after some work diving into selinon, I have one question that why not selinon task just use celery task?
Here is my idea:
1. selinon dispatcher keep using celery task for calling one flow,  so when calling a flow, a new dispatch task worker is invoked.
2. Task in flow is also celery task. So selinon dispatcher use send_task to call task in the flow and subflow, and use celery asyncResult.get() to approach task dependency. For example, task3 depends on task1 and task2, so just call async_result_of_task1.get() and async_result_of_task2.get(), the wait time is reasonable because the longest time of task1 and task2 is always needed. Retry of task can be reached by just celery task retries. 
3. One disadvantages of this model is the workflow throughput. The amount of dispatcher workers need to be greater than the max concurrency of all flow request. But I think this can be solved by coroutines such as greenlet（not sure）. 

I know maybe there are some irresistible reason that selinon choose not to use celery task, I wonder the design consideration bebind it.

**Comment by fridex** [comment]
> In the past few days, I have been searching and comparing list of distributed task flow engins support dynamic linking. At last, I found selinon is just what I want. It is a greate job! 

Thanks! Glad to hear that! :) If you have some summarized report with constraints of various distributed task flow engines I would be really interesting in it. Moreover we could also share it with community in the docs.

> But after some work diving into selinon, I have one question that why not selinon task just use celery task?

Basically this was some kind of incremental development. First [our system](https://github.com/fabric8-analytics/fabric8-analytics-worker) used purely celery (internal development, you will not find it in logs) which in long term was not possible to easily extend and maintain when we wanted to add new tasks and task flows - that's why selinon was designed.

I don't recall any strict limitation on why not directly celery's tasks - we could do that, but semantically it was more suitable so selinon tasks do not share methods with celery's one, no strict compatibility requirements (e.g. method name clashes) and so. Also selinon does not support some celery's features (revoked tasks, celery's retries with arguments changes, ...) so it is less error prone and for things like tracing that selinon offers, it is also more transparent.

BTW selinon uses celery just for publishing messages and retrievieving task's state. If one day devs of selinon decide to drop celery support (unlikely now), the only thing to implement would be message publishing (kombu) and storing/retrieving task states.

> Here is my idea:
> 1. selinon dispatcher keep using celery task for calling one flow,  so when calling a flow, a new dispatch task worker is invoked.
> 2. Task in flow is also celery task. So selinon dispatcher use send_task to call task in the flow and subflow, and use celery asyncResult.get() to approach task dependency. For example, task3 depends on task1 and task2, so just call async_result_of_task1.get() and async_result_of_task2.get(), the wait time is reasonable because the longest time of task1 and task2 is always needed. Retry of task can be reached by just celery task retries. 
> 3. One disadvantages of this model is the workflow throughput. The amount of dispatcher workers need to be greater than the max concurrency of all flow request. But I think this can be solved by coroutines such as greenlet（not sure）. 

That could work, but there are few downsides:
1. Note that all tasks can be run conditionally (based on results of dependencies or by some external events). By scheduling all tasks at once, you would basically fill queues and all workers would just perform retry waiting for ready-to-execute tasks somewhere in the queue to finish.
2. Currently you can easily isolate workers that do only dispatcher tasks (by placing them on separate queues) and have the "workload" workers that do actual task code - you can scale them independently.
3. Monitoring of queues would be harder on task level - with the current approach you can see how many flows are currently being executed and how many tasks are scheduled (and also type of tasks if you place them on separate queues, which I recommend)
4. Indeed, the workflow throughput in overall would increase, but I would be curious about percentage.
5. Task flows in selinon are not strictly DAG (in fact I don't know about any open source solution that would support cyclic dependencies in flows, have you found some?). In the proposed idea it would be harder to deal with cyclic deps between tasks and flows.

Thanks for your interest! I like any interest and input from community ;)

**Comment by fridex** [comment]
@dusteye feel free to reopen if more input is needed.
